import { Response } from 'express';
import { AuthRequest } from '../../middleware/auth';
import * as service from './service_payment';
import { successResponse, paginatedResponse } from '../../utils/response';
import { recordAudit } from '../admin/service_audit';

async function audit(req: AuthRequest, action: string, error?: unknown) {
  await recordAudit({ userId: req.user!.id, userRole: req.user!.role, module: 'Payment', action,
    entity: 'Payment', entityId: req.params.id ? String(req.params.id) : undefined,
    status: error ? 'Failed' : 'Success', level: error ? 'error' : 'info',
    errorMessage: error instanceof Error ? error.message : undefined, ipAddress: req.ip,
    userAgent: req.headers['user-agent'], requestUrl: req.originalUrl, httpMethod: req.method });
}
async function run(req: AuthRequest, res: Response, action: string, work: () => Promise<unknown>) {
  try {
    const result = await work();
    await audit(req, action);
    res.json(result);
  } catch (error) {
    await audit(req, action, error);
    res.status(error instanceof service.PaymentError ? error.statusCode : 500).json({
      success: false, error: { message: error instanceof service.PaymentError ? error.message : 'Payment request failed. Please retry.' },
    });
  }
}
export class PaymentController {
  list = (req: AuthRequest, res: Response) => run(req, res, 'VIEW_PAYMENTS', async () => {
    const result = await service.getPayments(Number(req.query.page) || 1, Number(req.query.limit) || 10, req.user!, req.query.status as string);
    return paginatedResponse(result.payments, result.page, result.limit, result.total);
  });
  getById = (req: AuthRequest, res: Response) => run(req, res, 'VIEW_PAYMENT', async () => {
    const payment = await service.getPaymentById(String(req.params.id), req.user!);
    if (!payment) throw new service.PaymentError('Payment not found', 404);
    return successResponse(payment);
  });
  summary = (req: AuthRequest, res: Response) => run(req, res, 'VIEW_PAYMENT_SUMMARY',
    async () => successResponse(await service.getFinanceSummary(req.user!)));
  simulate = (req: AuthRequest, res: Response) => run(req, res, 'SIMULATE_PAYMENT', async () => {
    const payment = await service.simulatePayment(String(req.params.id), req.user!, req.body?.outcome);
    return successResponse(payment, payment.status === 'PAID' ? 'Simulation successful. No money transferred.' : 'Simulated failure. You can retry.');
  });
  disabled = (req: AuthRequest, res: Response) => run(req, res, 'REJECT_MANUAL_PAYMENT', async () => {
    throw new service.PaymentError('Charges are generated by booking approval. Use the tenant payment simulation.', 403);
  });
}

